parameters:
  lr: 0.005
  gamma: 1
  batch_size: 64
  weight_decay: 0.0001
  epoch_number: 300
  realization_number: 20
  encoder_net: {input_dim: 3477, hidden_dims: [], output_dim: 50}
  prediction_net: {input_dim: 50, hidden_dims: [50], output_dim: 1}
